[functions]
  external_node_modules = ["express", "cors"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/index/:splat"
[[redirects]]
  from = "/style.css"
  to = "/style.css"
  status = 200
[[redirects]]
  from = "/script.js"
  to = "/script.js"
  status = 200